### ISSUE TITLE
Possível problema de relativização dos paths

### ISSUE THREAD

**Issue by Mazuh** [ccsa-ufrn/PosGraduacao#3]
Ao tentar executar o ```runserver.py``` na raíz do repositório (ao invés da raíz do virtualenv), o terminal imprime:

> ERROR:root:Failed to find Minerva/env/api_keys.json
> Traceback (most recent call last):
>   File "MinervaEnv/runserver.py", line 6, in <module>
>     from Minerva import app
>   File "/home/mazuh/Projetos/Minerva/MinervaEnv/Minerva/__init__.py", line 8, in <module>
>     import Minerva.views
>   File "/home/mazuh/Projetos/Minerva/MinervaEnv/Minerva/views.py", line 9, in <module>
>     import Minerva.util.apisistemas_oauth2client as api_sistemas
>   File "/home/mazuh/Projetos/Minerva/MinervaEnv/Minerva/util/apisistemas_oauth2client.py", line 22, in <module>
>     CLIENT_ID     = sinfo_api_dict['client-id']
> TypeError: 'NoneType' object is not subscriptable

Talvez os paths não estejam relativizados o suficiente. E isso pode dar problema no deploy.

Se for só esse path dando problema, tudo bem, porque esse json é (ou deveria ser) temporário.

**Comment by Mazuh** [comment]
Resolvido ao dockerizar o deploy no server. Mas a falta de relatividade ainda pode ser problemática em outros pontos.
